index grid
zeckson/htmlacademy-gllacy pull request #1
Opened 2020-11-05 15:59 UTC by webdotG

2020-11-05 16:37 UTC, zeckson requested changes

2020-11-05 16:37 UTC, zeckson commented on index.html
> +        <h6>Новинки</h6><!--не знаю как правильно сделать заголовок-->
Так его точно делать нельзя, т.к. внутри `ul` не может быть ничего кроме `li`
Новинки это разве не элемент меню?

2020-11-05 16:37 UTC, zeckson commented on index.html
> +        <input type="search" value="Что ищем?">
Это не `value` а `placeholder`

2020-11-05 16:37 UTC, zeckson commented on index.html
> +      <div class="user-login__wrapper">
Предлагаю внести этот блок отдельно из меню

2020-11-05 16:37 UTC, zeckson commented on index.html
> +          <input type="password" value="Пароль" required>
Это не `value` а `placeholder`

2020-11-05 16:37 UTC, zeckson commented on index.html
> +          <input type="email" value="Электронная почта" required>
Это не `value` а `placeholder`

2020-11-05 16:54 UTC, webdotG commented on index.html
> +        <h6>Новинки</h6><!--не знаю как правильно сделать заголовок-->
исправил

2020-11-05 16:55 UTC, webdotG commented on index.html
> +        <input type="search" value="Что ищем?">
исправил

2020-11-05 16:56 UTC, webdotG commented on index.html
> +      <div class="user-login__wrapper">
объясни пожалуйста зачем?

2020-11-05 16:57 UTC, webdotG commented on index.html
> +          <input type="password" value="Пароль" required>
исправил

2020-11-05 16:57 UTC, webdotG commented on index.html
> +          <input type="email" value="Электронная почта" required>
исправил

2020-11-05 17:10 UTC, zeckson commented on index.html
> +      <div class="user-login__wrapper">
Чтобы не смешивать элементы меню и диалоги

2020-11-05 20:17 UTC, webdotG commented on index.html
> +      <div class="user-login__wrapper">
исправил

2020-11-06 17:33 UTC, zeckson requested changes
Давай попробуем пока избавиться от ненужных `<br>`

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <!--не знаю как сверстать счетчик выбранных товаров-->
`<span>` например

2020-11-06 17:33 UTC, zeckson commented on index.html
> +        <h1>Крем-брюле и пломбир<br>
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <li><h1>Шоколадный пломбир<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <li><h1>Пломбир с помадкой<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>При покупке 2 кг любого фруктового мороженого, добавим<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>При покупке 2 кг пломбира, добавим в ваш заказ упаковку<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>Сливочное с апельсиновым<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>Сливочно-кофейное с кусочками<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>Сливочно-кофейное с кусочками<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>Сливочное крем-брюле с<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +    <h4>Магазин Глейси — это онлайн и офлайн магазин по продаже мороженого собственного<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          Все наше мороженое изготавливается на собственном<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          производстве, с использованием современного оборудования<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          Закупка ингредиентов производится только у проверенных<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          фермерских хозяйств и компаний, с которыми нас связывает<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          Для приготовления мороженого используются настоящие<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          сливки и молоко высочайшего качества. Все дополнительные<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          ингредиенты и добавки произведены из натурального,<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          Доставка нашего мороженого до заказчиков осуществляется<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +          в специальном термопаке, который не дает мороженому<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>Адрес главного офиса<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-06 17:33 UTC, zeckson commented on index.html
> +      <p>ул. Большая Конюшенная<br>
Можно обойтись без `<br>`
https://up.htmlacademy.ru/htmlcss/17/examples_br#

2020-11-09 14:46 UTC, zeckson approved these changes
Отлично! Погнали дальше!

2020-11-09 14:46 UTC, merged