fonts/img
zeckson/htmlacademy-gllacy pull request #2
Opened 2020-11-09 16:52 UTC by webdotG

2020-11-09 20:14 UTC, zeckson requested changes
Имена файлов должны соответствовать базовому критерию (Б14)[https://up.htmlacademy.ru/htmlcss/17/criteries#basic-14]

2020-11-09 20:14 UTC, zeckson commented on css/style.css
> +  color: rgba(0, 0, 0, 1);
Свойство `color` наследуется?

2020-11-10 08:21 UTC, zeckson requested changes
Пропала карта

2020-11-10 08:21 UTC, zeckson commented on index.html
> -    <img class="location-map" src="https://fakeimg.pl/1200x430/" alt="карта">
Куда карта пропала?

2020-11-10 08:21 UTC, zeckson commented on index.html
> +      <h4>ул. Большая Конюшенная
Почему это заголовок?

2020-11-10 14:14 UTC, zeckson requested changes
Нужно поправить картинку.
Так же предлагаю подключить `normalize.css` (https://up.htmlacademy.ru/htmlcss/17/criteries#advanced-5)
И использовать по возможности минимально необходимое кол-во свойств css, например убрать лишние наследуемые свойства такие как `color`

2020-11-10 14:14 UTC, zeckson commented on index.html
> +    <li><img src="img/white%20chocolate.jpg" width="267" height="267" alt="клубничное с присыпкой">
не загрузилась картинка

2020-11-18 10:12 UTC, webdotG commented on css/style.css
> +  color: rgba(0, 0, 0, 1);
да
исправил

2020-11-18 10:12 UTC, webdotG commented on index.html
> -    <img class="location-map" src="https://fakeimg.pl/1200x430/" alt="карта">
и правда, исправил

2020-11-18 10:12 UTC, webdotG commented on index.html
> +      <h4>ул. Большая Конюшенная
ты что рассист ?))

2020-11-18 10:17 UTC, webdotG commented on index.html
> +    <li><img src="img/white%20chocolate.jpg" width="267" height="267" alt="клубничное с присыпкой">
исправил
и не понял где скачать  файл normalize

2020-11-18 11:32 UTC, zeckson requested changes
Чтобы найти `normalize.css` можно использовать Google.
Например так:
1. Заходишь на сайт [google.com](google.com)
2. Вводишь туда `normalize.css`
3. Выбираешь любой, например этот (https://necolas.github.io/normalize.css/)
4. Жмешь кнопку скачать
5. Кладешь файл в проект
6. Коммитишь и пушишь

2020-11-18 11:32 UTC, zeckson commented on css/style.css
> +.gifts{
Это что?

2020-11-18 16:09 UTC, webdotG commented on css/style.css
> +.gifts{
переопределение цвета
или я не понял вопрос

2020-11-18 16:12 UTC, zeckson commented on css/style.css
> +.gifts{
Почему 2 раза. Мы же вроде договорились:
> И использовать по возможности минимально необходимое кол-во свойств css, например убрать лишние наследуемые свойства такие как `color`

2020-11-18 16:14 UTC, zeckson commented on css/style.css
> +.gifts{
тоже самое надо исправить в `h1, h2, h3, h4, h5, h6` — не прописывать цвет для каждого, а задать один общий базовый для всего текста, и переопределять только там, где нужно.

2020-11-18 16:25 UTC, zeckson requested changes
- [ ] не дублировать свойства, которые наследуются
- [ ] убрать свойства, которые определены уже в `normalize.css`

2020-11-18 16:25 UTC, zeckson commented on css/style.css
> +  margin: 0;
Это делает `normalize`, можно убрать

2020-11-18 16:25 UTC, zeckson commented on css/style.css
> +  padding: 0;
Это делает `normalize`, можно убрать

2020-11-18 16:25 UTC, zeckson commented on css/style.css
> +  color: rgba(0, 0, 0, 1);
нет, не исправил

2020-11-18 16:25 UTC, zeckson commented on index.html
> +      <h4>ул. Большая Конюшенная
нет, а ты?)))

2020-11-19 08:01 UTC, webdotG commented on css/style.css
> +  margin: 0;
+

2020-11-19 08:02 UTC, webdotG commented on css/style.css
> +  padding: 0;
+

2020-11-19 08:22 UTC, zeckson requested changes
Супер!
Осталось только определить цвет текста по-умолачанию (см. комменты) и поедем дальше

2020-11-19 08:22 UTC, zeckson commented on css/style.css
>    line-height: 22px;
Здесь нужно определить дефолтный цвет текста (свойство `color`), которое будет дальше наследоваться у всех элементов внутри `body`

2020-11-20 19:33 UTC, zeckson approved these changes

2020-11-20 19:33 UTC, merged