grid index start
zeckson/htmlacademy-gllacy pull request #3
Opened 2020-11-23 13:00 UTC by webdotG

2020-11-24 12:27 UTC, zeckson requested changes
1. Куда-то пропал блок с мороженком:
![image](https://user-images.githubusercontent.com/259739/100093919-417bac80-2e69-11eb-9281-56d2c0e73b9d.png)

2. Куда-то пропала картинка с картой:
![image](https://user-images.githubusercontent.com/259739/100093976-5a845d80-2e69-11eb-8550-029adc16326c.png)

3. Надо поправить фоны:
![image](https://user-images.githubusercontent.com/259739/100094027-6cfe9700-2e69-11eb-8d71-75d80c5748a3.png)

4. Убрать ненужные врапперы (указал в ревью конкретные места)

Свёрстано хорошо, лишних блоков и классов становится всё меньше.

2020-11-24 12:27 UTC, zeckson commented on index.html
> +  <div class="header-wrapper">
Давай избавимся от этого блока

2020-11-24 12:27 UTC, zeckson commented on index.html
> +  <div class="main-wrapper">
Давай избавимся от лишних блоков. Блок `.main-wrapper` не нужен.

2020-11-24 12:27 UTC, zeckson commented on index.html
> +  <div class="footer-wrapper">
Давай избавимся от ненужных врапперов.

2020-11-24 21:06 UTC, webdotG commented on index.html
> +  <div class="header-wrapper">
+

2020-11-24 21:07 UTC, webdotG commented on index.html
> +  <div class="main-wrapper">
+

2020-11-24 21:07 UTC, webdotG commented on index.html
> +  <div class="footer-wrapper">
+

2020-11-25 18:17 UTC, zeckson requested changes
Всё лучше и лучше)))
Написал на что стоит обратить внимание.
Если будут вопросы, задавай, буду рад ответить.

2020-11-25 18:17 UTC, zeckson commented on css/style.css
> +  min-height: 375px;
Зачем футер так растянут? 
Давай его под контент сожмём?

2020-11-25 18:17 UTC, zeckson commented on index.html
> +    <a class="header-logo" href=""><img src="img/logo_gllacy.png" width="154" height="64" alt="logo"></a>
Что-то тут отступы поехали кажется, давай придерживаться [критерия 15](https://up.htmlacademy.ru/htmlcss/17/criteries#basic-15) чтобы тебе было проще читать, а мне проверять.
Надо поправить во всём файле. Для этого можно использовать сочетание клавиш `Ctrl+Alt+L`

2020-11-25 18:17 UTC, zeckson commented on index.html
> +        <li class="slide-first">
Давай, разметим один блок из списка, а остальные либо удалим, либо спрячем пока. Ок?

2020-11-25 18:17 UTC, zeckson commented on index.html
> +      <li><img src="img/chocolate.png" width="267" height="267" alt="Сливочно-кофейное">
Предлагаю разлепить эти элемент 
![image](https://user-images.githubusercontent.com/259739/100266625-3016cb00-2f63-11eb-9e8e-16f5db66638b.png)
при помощи: `justify-content: space-between;`

2020-11-28 09:27 UTC, webdotG commented on index.html
> +    <a class="header-logo" href=""><img src="img/logo_gllacy.png" width="154" height="64" alt="logo"></a>
+

2020-11-28 09:27 UTC, webdotG commented on css/style.css
> +  min-height: 375px;
Жека не понял,  что именно ты хочешь

2020-11-28 09:28 UTC, webdotG commented on index.html
> +        <li class="slide-first">
ок

2020-11-28 09:32 UTC, webdotG commented on index.html
> +      <li><img src="img/chocolate.png" width="267" height="267" alt="Сливочно-кофейное">
чот не хочет работать, разбираюсь в чем дело )))

2020-11-28 09:41 UTC, webdotG commented on index.html
> +      <li><img src="img/chocolate.png" width="267" height="267" alt="Сливочно-кофейное">
сделано )

2020-11-28 18:42 UTC, zeckson commented on css/style.css
> +  min-height: 375px;
Футер торчит вниз на лишних 200px. Предлагаю не задавать ему высоту

2020-11-30 07:23 UTC, zeckson reviewed
Ок. Давай поправим футер и дальше пойдём

2020-12-01 09:52 UTC, zeckson approved these changes
Ок. Погнали дальше.

2020-12-01 09:53 UTC, merged